# Generated by Django 5.2.5 on 2025-09-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "atomic_number",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "elements",
            },
        ),
        migrations.CreateModel(
            name="Feedstock",
            fields=[
                (
                    "feedstock_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "feedstocks",
            },
        ),
        migrations.CreateModel(
            name="PriceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "price_sources",
            },
        ),
        migrations.CreateModel(
            name="ElementFeedstockWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=16, null=True
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        db_column="atomic_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.element",
                    ),
                ),
                (
                    "feedstock",
                    models.ForeignKey(
                        db_column="feedstock_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.feedstock",
                    ),
                ),
            ],
            options={
                "db_table": "element_feedstock_weights",
                "unique_together": {("element", "feedstock")},
            },
        ),
        migrations.CreateModel(
            name="FeedstockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("unit", models.CharField(default="USD/unit", max_length=32)),
                (
                    "feedstock",
                    models.ForeignKey(
                        db_column="feedstock_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.feedstock",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pricesource",
                    ),
                ),
            ],
            options={
                "db_table": "feedstock_prices",
                "indexes": [
                    models.Index(
                        fields=["ts", "feedstock"], name="feedstock_p_ts_14a444_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feedstock", "ts"), name="uq_feedstock_ts"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ElementPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("unit", models.CharField(default="USD/unit", max_length=32)),
                (
                    "element",
                    models.ForeignKey(
                        db_column="atomic_number",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.element",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pricesource",
                    ),
                ),
            ],
            options={
                "db_table": "element_prices",
                "indexes": [
                    models.Index(
                        fields=["ts", "element"], name="element_pri_ts_6fff87_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("element", "ts"), name="uq_element_ts"
                    )
                ],
            },
        ),
    ]
